version: '3.8'
services:
  ecommerce-db:
    image: postgres:17
    ports: 
     - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nest
    networks:
     - ecommerce
networks:
  ecommerce:
